name: divvy
description: "Flutter application for tracking and splitting shared expenses among groups, roommates, and shared households."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  divvy_api_client:
    path: packages/divvy_api_client
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  get_it: ^9.2.0
  logger: ^2.6.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_signin_button: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
